version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - wordpress_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # WordPress + Custom REST API Plugin (Development)
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: 1
      WORDPRESS_URL: http://localhost
      WORDPRESS_TITLE: WordPress Development Site
      WORDPRESS_ADMIN_USER: admin
      WORDPRESS_ADMIN_PASSWORD: admin
      WORDPRESS_ADMIN_EMAIL: admin@example.com
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://localhost');
        define('WP_SITEURL', 'http://localhost');
        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);
    volumes:
      - wordpress_data:/var/www/html
      # Mount plugin source for hot reloading
      - ./wp-content/plugins/custom-rest-api/src:/var/www/html/wp-content/plugins/custom-rest-api/src
      - ./wp-content/plugins/custom-rest-api/package.json:/var/www/html/wp-content/plugins/custom-rest-api/package.json
      - ./wp-content/plugins/custom-rest-api/tsconfig.json:/var/www/html/wp-content/plugins/custom-rest-api/tsconfig.json
    depends_on:
      db:
        condition: service_healthy
    networks:
      - wordpress_network

  # phpMyAdmin (optional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress_password
    depends_on:
      - db
    networks:
      - wordpress_network

  # Development tools container
  dev-tools:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./wp-content/plugins/custom-rest-api:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run watch"
    networks:
      - wordpress_network

volumes:
  db_data:
    driver: local
  wordpress_data:
    driver: local

networks:
  wordpress_network:
    driver: bridge

